### ISSUE TITLE
[Compatibility] SW FFG Enhancements

### ISSUE THREAD

**Issue by Havoclivekiller** [prolice/swffgUI-cc#10]
A new module with enhancements was made for SW FFG. However, some stuff is broken due to the UI. For example, the ability to create datapads/bounties (journal entries).
![image](https://user-images.githubusercontent.com/21118924/118870038-6a47a080-b8e6-11eb-926c-667b320998f1.png)
![image](https://user-images.githubusercontent.com/21118924/118870074-73d10880-b8e6-11eb-8d71-a07149f2dadd.png)
![image](https://user-images.githubusercontent.com/21118924/118870087-76336280-b8e6-11eb-95d1-404ea9c47713.png)

**Comment by prolice** [comment]
v0.3.3.3
