### ISSUE TITLE
Issues reading text in a few places with UI on

### ISSUE THREAD

**Issue by SnoringMountain** [prolice/swffgUI-cc#11]
A few examples are below, the text colour needs to be more visible on the background in a lot of places. This is true with all of the themes.

![image](https://user-images.githubusercontent.com/73663905/119418278-8769de00-bcef-11eb-9f97-e71d99cfa872.png)

![image](https://user-images.githubusercontent.com/73663905/119418737-956c2e80-bcf0-11eb-8eba-3db58e4f78b4.png)

**Comment by prolice** [comment]
Thank for you contribution, I ll check that

**Comment by prolice** [comment]
I need more information, the screen shot are from specific module ?

**Comment by SnoringMountain** [comment]
The first was a pop up informing that I didn't have a required module, the
second was from the settings of the ffg star wars enhancements module, but
it was true for quite a lot of the settings screens
