### ISSUE TITLE
Window Size Issue

### ISSUE THREAD

**Issue by Bastlifa** [prolice/swffgUI-cc#14]
For some reason, this module shrinks the size of some of the popup windows, and doesn't always add a scroll to them, so, for example, I can't use the import button for FFG.

**Comment by prolice** [comment]
Hello,
Thx for your return, could you add a screenshot to your issue ?
I ll check it this week-end ;-)
BR,

**Comment by Bastlifa** [comment]
Hey, here's some screenshots. I noticed that on the rebel theme, there's no way to click, but on edge of the empire, you can just slightly get the top of the "Start Import" button with the mouse.

Normal UI Popout:
![Base Importer Popout](https://user-images.githubusercontent.com/19656160/144375579-4fbf597b-a69a-4540-8a6a-b7a71c4136da.JPG)

Rebel theme swffgui-cc:
![ui change importer](https://user-images.githubusercontent.com/19656160/144375641-e6a65e5a-18eb-4d19-a4cb-6fe4b7a270b3.JPG)

**Comment by prolice** [comment]
Ok I see, NPC importer is a new window to me so I have to create the entry keys for this window in my css file...
Thx for your help ;-)

**Comment by prolice** [comment]
There is a new update ;-) 1.3.3

**Comment by Bastlifa** [comment]
Nice, thanks. Works great.
