### ISSUE TITLE
Custom Themes clash with Cards UI

### ISSUE THREAD

**Issue by diegochica78** [prolice/swffgUI-cc#16]
**Any of the Custom themes that aren't the Black and White or Default clash with the Cards and Monk's Enhanced Journal UI.**
The Enhanced Journal problem is inherently less important since its an optional module, but the Cards UI is unreadable when using a Custom Theme and I was wondering if there could be some sort of fix for this.
Thanks!

**Comment by prolice** [comment]
fixed in v2.1.1 just released
