### ISSUE TITLE
[BUG] With Default skin the fonts of the character sheets are not correct

### ISSUE THREAD

**Issue by Jarlok2** [prolice/swffgUI-cc#17]
**Describe the bug**
When you choose in the module settings the "Default" skin and another font, for example "Eras", in the character sheets the text is normal, doesn't appear the "Star wars fonts". With other skins the fonts appear correctly.

**Desktop (please complete the following information):**
 - FoundryVTT: 9.249
 - Browser: Chrome and Firefox
 - Module Version 1.72
 
![image](https://user-images.githubusercontent.com/81709579/152698524-c71fef31-b8c6-4bea-8586-e3c3b1018c05.png)

**Comment by prolice** [comment]
Oh, yes default does not taking the settings into account --> default is made to avoid any problem link to any changes made by other skins ;-)
So it is on purpose
