### ISSUE TITLE
[BUG] Can't View / Edit Journal In Most Themes

### ISSUE THREAD

**Issue by RhapsodyInGeek** [prolice/swffgUI-cc#22]
**Describe the bug**
Cannot view Journal Pages with any UI skins except for "Imperial Black" and "Default".

**To Reproduce**
1. Go to Configure Settings > Star Wars User Interface.
2.  Set UI skin to any skin other than "Imperial Black" and "Default".
3. Access Journal. Attempt to view or edit pages.

**Expected behavior**
Journals should be both viewable and editable under any theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/44485952/205601085-a62a1eed-2899-4aef-9835-fc040d4b9337.png)
![image](https://user-images.githubusercontent.com/44485952/205601246-55c9420a-6ded-4b5e-a341-99c3578ecd78.png)
![image](https://user-images.githubusercontent.com/44485952/205601337-bd69f04c-13ef-419a-83b0-0ccf6d679253.png)
![image](https://user-images.githubusercontent.com/44485952/205601400-6a579f71-28cb-43e8-b46a-d4baf2b1330a.png)
![image](https://user-images.githubusercontent.com/44485952/205601470-3e25bd1e-a216-4c5d-b2ef-961af0bdbe44.png)

**Desktop (please complete the following information):**
 - FoundryVTT Version 10 Build 291
 - Star Wars FFG Version 1.80-alpha5
 - UI Module Version 2.2.1

**Additional context**
All screenshots are of the same exact Journal Entry and Page. Pages can be added. They cannot be edited in the themes they do not show up in.

**Comment by prolice** [comment]
v2.2.2 has been released
