### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sunspoticus** [prolice/swffgUI-cc#23]
**Describe the bug**
It appears as if Skin/UI isn't being sent to players completely. Some players see nothing, others only get fragments (as evidenced by screenshots).

**To Reproduce**
1. Create a new world and activate this module
2. Have a player connect.
3. Regardless of skin selected, players only see default foundry UI

**Expected behavior**
Players would be able to see the active skin 

**Screenshots**
![GM](https://user-images.githubusercontent.com/16306427/206623589-5c2e4d9d-9d75-47ca-9de1-c9605313c428.png)
![Player1](https://user-images.githubusercontent.com/16306427/206623613-e8c68e0a-c52b-48c2-8717-656f814a8c2c.png)
![Player2](https://user-images.githubusercontent.com/16306427/206623620-c6352756-07e8-495f-a71d-99ee7227020c.png)

**Desktop (please complete the following information):**
 - **FoundryVTT:** 10.291
 - **Browser:** Edge
 - **Module Version:** 2.2.1

Thanks for your attention...

**Comment by prolice** [comment]
It is not a bug, the settings has "client" as scope:
So every client/player or GM can have its own settings.
You player have to go into the settings and activate the same skin as you.

**Comment by prolice** [comment]
Btw you can download the last version 2.2.3 now
it will fix the display on the pause text to looks like auberesh pause text ;-)
Have fun
