### ISSUE TITLE
[BUG] Compatibility with FFG SW Enhancements's Openning Crawl

### ISSUE THREAD

**Issue by sanpats** [prolice/swffgUI-cc#24]
**Describe the bug**
When use other themes other than "Default", the font used in Opening Crawl will be changed into a wrong font.

**To Reproduce**
1. Change UI them to any other than Default.
2. Make Opening Crawl via FFG SW Enhancement module.
3. Launch the opening crawl

**Expected behavior**
Change UI themes should not affect Opening Crawl.

**Screenshots**
Correct One:
![image](https://user-images.githubusercontent.com/22677493/229825630-66c9e1df-be8b-46ec-b7f9-fb8722344fe0.png)

Wrong One: 
![image](https://user-images.githubusercontent.com/22677493/229825283-f738e371-4866-4bfa-a5ca-f6b701b3dff7.png)

**Desktop (please complete the following information):**
 - FoundryVTT: 10.291
 - Browser Edge, Chrome
 - Module Version 2.2.3

**Additional context**
-

**Comment by sanpats** [comment]
![image](https://user-images.githubusercontent.com/22677493/229825029-e765bc7e-f1bb-41d5-964f-1c65d194a927.png)

**Comment by prolice** [comment]
The main feature of the UI module is the possibility to change the font all over the app.
It doesn't know how much module are install and of course which one.
So I think that's an issue to "FFG SW Enhancement module" to assure that their display is conform to the expectation, no matters what the other module do.
