### ISSUE TITLE
[BUG] Unable to select scene from top bar scene navigation - Forge

### ISSUE THREAD

**Issue by Vrarrdata** [prolice/swffgUI-cc#26]
**Describe the bug**
Unable to select a scene from top bar scene navigation - Forge

**To Reproduce**
Steps to reproduce the behaviour:
1. Update the Star Wars FFG system module manually into Forge using the import wizard
2. Update the Game from 10.303 to 11.308
3. Activate the SWFFGUI Module

**Expected behaviour**
Being able to left and right-click the Scene Navigation Bar

**Screenshots**
Without module
![ezgif-2-966f35ac1a](https://github.com/prolice/swffgUI-cc/assets/35790030/810780e7-66d0-4e39-ba4d-930d94e9091f)

With Module
![ezgif-2-4e56ce44b3](https://github.com/prolice/swffgUI-cc/assets/35790030/f1fcd197-dfcc-4f14-8c78-5ecfd72f997f)

**Desktop (please complete the following information):**
 - FoundryVTT: 11.308
 - Browser: Firefox
 - Module Version 2.2.4

**Additional context**
It worked in 10.303 in Forge

**Comment by prolice** [comment]
Bug fixed in version 2.3.0
