### ISSUE TITLE
Imperial Black theme roll total font color

### ISSUE THREAD

**Issue by dean3c** [prolice/swffgUI-cc#29]
The roll totals when using the Imperial Black theme are off-white on white and very difficult to see, almost like a ghost image on an LCD type screen. It would be helpful to change it to a darker color that is legible in a future update, as that theme is very clean otherwise.

**Comment by prolice** [comment]
Sorry,
I dont understand where is it ?
Do you have a screen shot ?
Thx

**Comment by dean3c** [comment]
That would have been helpful, sorry!
<img width="310" alt="chat_window" src="https://github.com/prolice/swffgUI-cc/assets/52510954/d7094809-212b-4603-bc13-7ffe008d4d25">
The number total in the red bordered box. 

Perhaps this is just an issue on my system though? If you know where that field is in the css file, perhaps I could just make a local edit to the module and not require its inclusion in the next version update. 

Thanks for your help and making this amazing module!

**Comment by prolice** [comment]
It seems that you have anothe module activate.
This module change colors of the chat windows like the title of the chat window.
I dont have the same behaviour:
![image](https://github.com/prolice/swffgUI-cc/assets/48445910/d1c6dd4c-3190-4279-a7b6-f9feda48b2a6)
I suggest to deactivate all the module to detect which module cause this (if you dont know already).

**Comment by dean3c** [comment]
In swffg.css, it was Lines 1572-1573 that I was looking for, setting white to another color:

1572     .dice-roll .dice-total {
1573	    color:white;
	
The reason for the conflict is actually the system I am using this module with, sw5e. For some reason it interacts with the swffg Imperial Black theme and adds a white background to that dice total block. But setting 1573 to red solved it for me. 
<img width="287" alt="red_fix" src="https://github.com/prolice/swffgUI-cc/assets/52510954/06c0ea08-cb53-4cd9-a82b-343f22fcc338">

Thanks again for your great module designs.
