### ISSUE TITLE
[Feature] Journal Notes Different looks

### ISSUE THREAD

**Issue by Havoclivekiller** [prolice/swffgUI-cc#6]
Could be possible to implement some different looks for Journal Notes? Like a Datapad look - frame, background and text color? Here's some examples:
![image](https://user-images.githubusercontent.com/21118924/117108859-16847580-ad84-11eb-88b1-8e32ae725dfd.png)
![image](https://user-images.githubusercontent.com/21118924/117108912-269c5500-ad84-11eb-952c-91bfdb7eeea6.png)
![image](https://user-images.githubusercontent.com/21118924/117109030-5186a900-ad84-11eb-9f3f-03d8fff459c7.png)

**Comment by prolice** [comment]
Hello,
I already thinking about this feature but I have to create a datapad design by myself cause there are all copyrighted...
So, if I can find a datapad design in Creative Common Licence, i ll add it ;-)

**Comment by Havoclivekiller** [comment]
If you find a graphic designer, I might find some cash to fund a datapad template.

**Comment by prolice** [comment]
> If you find a graphic designer, I might find some cash to fund a datapad template.

I have contact someone to get it free and I m waiting for answer ... evreything I have done was for free, I want to keep this way
Thank you for your offer, I think it will be not necessary ...

**Comment by prolice** [comment]
Now in a specific module --> Star Wars FFG enhancement
