### ISSUE TITLE
[Theme] Black and White Theme

### ISSUE THREAD

**Issue by Havoclivekiller** [prolice/swffgUI-cc#7]
Could you add another theme? Maybe call it Imperial Black? ;)
![image](https://user-images.githubusercontent.com/21118924/117248085-aaffde00-ae3f-11eb-8ab6-7a729557a335.png)
![image](https://user-images.githubusercontent.com/21118924/117248094-b18e5580-ae3f-11eb-99e5-c7fb58c2d54c.png)
![image](https://user-images.githubusercontent.com/21118924/117248124-b8b56380-ae3f-11eb-861e-0a3e32221b16.png)
![image](https://user-images.githubusercontent.com/21118924/117248157-c2d76200-ae3f-11eb-82b9-1724e371b05b.png)

**Comment by prolice** [comment]
That's a good idea, i keep it in my mind ...
I plan to work on the module in about 2 or 3 weeks from here ;-)

**Comment by TheMOELANDER** [comment]
Hey, with minimal changes, could you do this for the galactic republic as well? You know for clone wars themed campaigns. That would be awesome.
